### PR TITLE
Added JSPM support

### PR DESCRIPTION
**Pull request by davidpronk**
JSPM support as described in stefanpenner/es6-promise#248

### CODE REVIEW

**Comment by stefanpenner** [comment]
@guybedford does this look correct?

**Comment by guybedford** [comment]
`jspm install npm:es6-promise` seems to be running ok for me, in which case this override shouldn't be necessary, and would actually break that workflow for users running it.

**Comment by guybedford** [comment]
@stefanpenner thanks for the ping sir.

**Comment by davidpronk** [comment]
It seems to work just fine now. Might have been a misconfiguration in my local setup.

**Pull request closed without merging**
