### PR TITLE
Use setTimeout(0)

### PR DESCRIPTION
**Pull request by senaev**
In order to solve problems, described in issue stefanpenner#350

### CODE REVIEW

**Comment by senaev** [comment]
@stefanpenner check this please

**Comment by stefanpenner** [comment]
LGTM, node 4 failure is unrelated (it is related to our test runner no longer supporting node 4..), so merging.

**Comment by senaev** [comment]
@stefanpenner can you publish a new release with this changes?

**Comment by senaev** [comment]
@stefanpenner ping

**Pull request merged**
