### PR TITLE
fix: fixed sorting of package.json with `fixpack`, added jsdelivr/unpkg

### LINKED ISSUE #342: Add `unpkg` and `jsdelivr` properties to package.json which point at dist version
http://unpkg.com/es6-promise currently serves non-minified version

### PR DESCRIPTION
**Pull request by niftylettuce**
closes #342

### CODE REVIEW

**Comment by niftylettuce** [comment]
once this PR is merged I can remove the comment here <https://github.com/niftylettuce/frisbee#vanillajs>

**Comment by niftylettuce** [comment]
also I saw that you are missing a "homepage" property in `package.json` - you may want to add that too!

**Comment by stefanpenner** [comment]
Nice thanks. I’ll release once I’m back at my laptop

**Comment by niftylettuce** [comment]
ping me once you release! thanks @stefanpenner

**Comment by niftylettuce** [comment]
or feel free to add me to npm and github, I can gladly help maintain this

**Comment by stefanpenner** [comment]
add homepage prop: https://github.com/stefanpenner/es6-promise/pull/344

Also, fixpack is pretty cool!

**Comment by stefanpenner** [comment]
> or feel free to add me to npm and github, I can gladly help maintain this

Reducing buss factor is always good, do you have any specific ideas or just helping mitigate the buss factor problem that node modules often have?

**Comment by stefanpenner** [comment]
released as v4.2.6 🎉

**Comment by niftylettuce** [comment]
thank you 👍

**Pull request merged**
