### PR TITLE
Drop `dist` from git repo

### LINKED ISSUE #231: drop dist from git repo
legacy thing, makes commits and merges all messy and stuff.

We should publish built artifacts somewhere easily accessible to non-npm users

### PR DESCRIPTION
**Pull request by sotojuan**
Fixes #231, if this is what you meant :-)

### CODE REVIEW

**Comment by stefanpenner** [comment]
It requires a second part, which is publishing to S3 or something on builds so we do have this output.  @fivetanley may have time to help, as he did it for RSVP.js

**Comment by sotojuan** [comment]
Cool! What about something like https://unpkg.com/?

**Comment by stefanpenner** [comment]
@sotojuan oh, I have not seen that before. Looks like it would solve the issue.

**Comment by stefanpenner** [comment]
@sotojuan actually a quick read yields:

>  All you need to do is include your UMD build in your npm package (not your repo, that's different!).

Which seems like what we are attempting to avoid.

**Comment by sotojuan** [comment]
Hey, I probably won't be able to work on this so I'm closing the PR. Sorry!

**Pull request closed without merging**
