### PR TITLE
Fix readme links to dist downloads

### PR DESCRIPTION
**Pull request by g-k**
The minified prod version doesn't exist.

### CODE REVIEW

**Comment by stefanpenner** [comment]
hmm, likely a bug. Will address

**Comment by HarryPehkonen** [comment]
I just put this into my browser, and got a 404:

[https://raw.githubusercontent.com/stefanpenner/es6-promise/master/dist/es6-promise.js](https://raw.githubusercontent.com/stefanpenner/es6-promise/master/dist/es6-promise.js)

I had created a PR (#209) that points to [https://github.com/stefanpenner/es6-promise/raw/master/dist/lib/es6-promise.js](https://github.com/stefanpenner/es6-promise/raw/master/dist/lib/es6-promise.js), which works, but that seems so different.  I don't know if Github changed the way links need to be created.

**Comment by snuggs** [comment]
@stefanpenner  should be able to close this. yes?

**Comment by snuggs** [comment]
@stefanpenner  should be able to close this. yes?

**Comment by stefanpenner** [comment]
@snuggs thank you sir. Also, Hey! its been ages!

**Pull request closed without merging**
