### PR TITLE
Only use vertxNext() when it is not undefined

### PR DESCRIPTION
**Pull request by ThomasConner**
When creating a build with webpack or browserify the `vertx` module is ignored. However, some environments attempt to use it resulting a promise that is not resolved or rejected. This change makes sure that `vertxNext` is defined otherwise it will use `useSetTimeout()`.

### CODE REVIEW

**Comment by stefanpenner** [comment]
This seems very reasonable:

> However, some environments attempt to use it resulting a promise that is not resolved or rejected.

can you share more about this, i would like to correctly understand these scenarios.

**Comment by ThomasConner** [comment]
I help develop a [Titanium Library](https://github.com/Kinvey/titanium-sdk) at [Kinvey](http://www.kinvey.com). In a Titanium app environment, `browserWindow` is `undefined` but a `require` function is available. This causes [L112](https://github.com/stefanpenner/es6-promise/blob/master/lib/es6-promise/asap.js#L112) in [asap.js](https://github.com/stefanpenner/es6-promise/blob/master/lib/es6-promise/asap.js) to be `true`. We use Webpack to bundle the library together which ignores the `vertx` module due to `"browser": { "vertx": false }` set in the [package.json](https://github.com/stefanpenner/es6-promise/blob/master/package.json#L53). When we run our library in a Titanium environment, we receive the following error `undefined is not a function (evaluating 'vertxNext(flush)')` because the `vertx` module is ignored providing an empty object and setting `vertxNext` to an `undefined` value.

**Comment by stefanpenner** [comment]
@ThomasConner awesome thank you very much for that explanation. 

I am about to go camping, I will review this and most likely :shipit: later this weekend.

**Comment by stefanpenner** [comment]
releases as v4.0.4

**Comment by ThomasConner** [comment]
Thanks for merging and release!

**Comment by z-vr** [comment]
@ThomasConner @stefanpenner I'm trying to find out more information about `vertx`, what is it? npm `vertx` package does not exist...

**Comment by ThomasConner** [comment]
@z-vr http://vertx.io/

**Comment by z-vr** [comment]
@ThomasConner I thought so but it's not in `package.json`, so does it mean that in is only enabled if a developer manually inserted `vertx` into the page? because `vertx` isn't even a package.

**Comment by ThomasConner** [comment]
@z-vr It looks like it. I am not sure since I am not using it.

**Comment by stefanpenner** [comment]
> @ThomasConner I thought so but it's not in package.json, so does it mean that in is only enabled if a developer manually inserted vertx into the page?

vertx is an alternative environment (typically server side) for running a suite of languages on the JVM, one of which is JavaScript. So it isn't something to insert on the page, rather it could be seen as a alternative to node.js

**Pull request merged**
