### PR TITLE
Provide separate auto-polyfill version of this module

### PR DESCRIPTION
**Pull request by kevinoid**
This pull request provides a mechanism for users to load a version of this module which automatically installs the polyfill, separately from the default non-automatic version, as outlined in https://github.com/jakearchibald/es6-promise/pull/126#issuecomment-120542090

It uses `require('es6-promise/auto')` instead of `require('es6-promise/polyfill')` so that it does not directly conflict with the [es-shim-api API Contract][es-shim-api] in case support is later added.  I'm open to changing this if another name is preferred.

In addition to the Node/Browserify file, a UMD file which triggers automatic polyfill installation is also provided.

Thanks for considering,
Kevin

Fixes: #140
Alternative-to: #126 

Note to reviewer:  This commit reduces `dist/es6-promise.min.js` from 18kB to 6.4kB by mangling the names.  I'm not sure why the previous commit was not mangled, since `mangle: false` is not passed to `broccoli-uglify-js`, but if it was intentional, I can fix and resubmit.

[es-shim-api]:  https://github.com/es-shims/es-shim-api#api-contract

### CODE REVIEW

**Comment by stefanpenner** [comment]
sg

@jakearchibald r?

**Comment by stefanpenner** [comment]
I will include this as part of 4.0 (hoping to release that this weekend)

**Comment by kevinoid** [comment]
Sounds great, thanks!

**Comment by kevinoid** [comment]
I had some time this evening and was curious about the behavior of other popular Promise libraries which could serve as polyfills.  From some quick investigation, here's what I've found:

Library                  | Browser Polyfill      | Un-Polyfill                 | Node Polyfill
------------------------ | --------------------- | --------------------------- | -------------
[bluebird][bb]           | [Unconditional][bb-i] | [`.noConflict()`][bb-u]     | None
[Native Promise Only][n] | [If falsy][n-i]       | None                        | [If falsy][n-i]
[promise][p]             | [If `undefined`][p-i] | None                        | None
[Q][q]                   | [None][q-i]           | [`.noConflict()` of Q][q-u] | None
[RSVP.js][r]             | None                  | None                        | None
[when.js][w]             | [Unconditional][w-i] from [when/es6-shim/Promise][w-id] only | None | [Unconditional][w-i] from [when/es6-shim/Promise][w-id] only
[vow][v]                 | None                  | None                        | None

I think the behavior implemented in this PR appears to be similar to the behavior of [when.js][w].  I don't have an opinion about whether it is the best behavior.  Just thought it was worth considering any established conventions.

[bb]: https://github.com/petkaantonov/bluebird
[bb-i]: https://github.com/petkaantonov/bluebird/blob/v3.3.1/src/promise.js#L70
[bb-u]: https://github.com/petkaantonov/bluebird/blob/v3.3.1/src/bluebird.js#L4
[n]: https://github.com/getify/native-promise-only
[n-i]: https://github.com/getify/native-promise-only/blob/0.8.0-a/lib/npo.src.js#L8
[p]: https://github.com/then/promise
[p-i]: https://github.com/then/promise/blob/7.1.1/polyfill.js#L5
[q]: https://github.com/kriskowal/q
[q-i]: https://github.com/kriskowal/q/issues/464
[q-u]: https://github.com/kriskowal/q/blob/v1.4.1/q.js#L70
[r]: https://github.com/tildeio/rsvp.js
[w]: https://github.com/cujojs/when
[w-i]: https://github.com/cujojs/when/blob/3.7.7/es6-shim/Promise.browserify-es6.js#L11
[w-id]: https://github.com/cujojs/when/blob/master/docs/es6-promise-shim.md
[v]: https://github.com/dfilatov/vow

**Comment by naoufal** [comment]
@stefanpenner Hey just wanted to check-in on the status of this PR. :smiley: 

What's the status on the release of 4.0?

**Comment by stefanpenner** [comment]
> What's the status on the release of 4.0?

When I have time

**Comment by naoufal** [comment]
@stefanpenner No worries, I know how it goes. 

If there are things you feel you can delegate, I'd be glad to lend a hand.

**Comment by stefanpenner** [comment]
I'll take a look this weekend, and see what can be delegated. I first must restore my memory on this project, so I can remember where i left off.

**Comment by naoufal** [comment]
Sounds good to me.

Didn't mean to rush you, just wanted to know whether or not this PR was still active.

**Comment by stefanpenner** [comment]
@naoufal would love extra help, so no worries :)

**Comment by stefanpenner** [comment]
updated for latest build updates: https://github.com/stefanpenner/es6-promise/pull/230

**Comment by kevinoid** [comment]
Thanks for updating and merging this PR @stefanpenner!  I appreciate the extra effort for making this non-trivial API change.  It looks great!

**Pull request closed without merging**
